[workspace]
resolver = "2"
members = [
	"asm-playground",
	"doasm",
	"dtemu",
	"dt-bindings",
	"yarer",
	"unasm-derive",
	"cartridge",
	"readcart",
	"asane",
	"paracpm", "libemu-crossterm", "libemu", "libemu-3ds", "libemu-psp",
]

[profile.release]
debug = true
