[package]
name = "dtemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.6.0"
bitflags = "2.4.2"
futures = "0.3.30"
