[package]
name = "libemu-psp"
version = "0.1.0"
edition = "2021"

[dependencies]
libemu = { version = "0.1.0", path = "../libemu", default-features = false }
#libemu = { version = "0.1.0", path = "../libemu" }
psp = { version = "0.3.9" }
