[package]
name = "paracpm"
version = "0.1.0"
edition = "2021"

[dependencies]
asane = { version = "0.1.0", path = "../asane" }
clap = { version = "4.5.4", features = ["derive"] }
futures-lite = "2.3.0"
